import pandas as pd

from dags.order_notifications.get_order_data.get_order_list_for_shop import (
    get_order_list,
    parse_order,
    get_orders_for_store,
)
import vcr
import json
from datetime import datetime, timedelta


RECORD_MODE = "none"  # "new_episodes"


@vcr.use_cassette(
    "dags/order_notifications/get_order_data/endpoint_wrappers/cassettes/pickup_overview.yaml",
    record_mode=RECORD_MODE,
    allow_playback_repeats=True,
)
def test_get_orders_for_store_returns_dataframes():
    orders = get_orders_for_store(287, datetime.now())
    assert len(orders) == 3
    assert type(orders[0]) == pd.DataFrame


@vcr.use_cassette(
    "dags/order_notifications/get_order_data/endpoint_wrappers/cassettes/pickup_overview.yaml",
    record_mode=RECORD_MODE,
    allow_playback_repeats=True,
)
def test_get_order_list_for_shop_returns_empty_list_for_no_orders_at_shop():
    order_list = get_order_list(287, datetime.now() - timedelta(days=1))
    assert order_list == []


@vcr.use_cassette(
    "dags/order_notifications/get_order_data/endpoint_wrappers/cassettes/pickup_overview.yaml",
    record_mode=RECORD_MODE,
    allow_playback_repeats=True,
)
def test_get_order_list_returns_orders_as_list_of_dataframes():
    order_list = get_order_list(287, datetime.now())
    print(order_list)
    assert len(order_list) == 3


def test_parse_order():
    order = parse_order(EXAMPLE_ORDER_DICT)
    assert [str(x) for x in order.iloc[0].values] == [
        "2.25",
        "500 g",
        "Bio Apfel Elstar vom Bio-Obsthof Augusting",
        "Felix Weth",
        "01781896873",
        "22798",
    ]


def pprint(json_string):
    print(json.dumps(json_string, indent=4, sort_keys=True))


EXAMPLE_ORDER_DICT = {
    "allow_callback": 0,
    "comment": "Hinterhof, linke T\u00fcr, 4. Stock",
    "dateCreated": "2021-12-17T22:01:37+01:00",
    "fkUserId": {
        "birthdate": "1979-12-15T00:00:00+01:00",
        "created_at": "2021-06-25T12:31:09+02:00",
        "email": "felix.weth@gmail.com",
        "emailCanonical": "felix.weth@gmail.com",
        "enabled": True,
        "firstname": "Felix",
        "id": 8133,
        "lastLogin": "2021-12-17T21:22:49+01:00",
        "name": "Weth",
        "password": "x4Sa1OeINDU/JJDXAP9rsmlRMlvhdDa8lngKuC8qj+cnLoINtR2NMw==",
        "phone": "01781896873",
        "roles": ["ROLE_BUYER"],
        "salt": "i9yeuiJYAB3fpXgqztV2Y.hjIMJmXLcvJAj/OhFdGQg",
        "username": "felix.weth@gmail.com",
        "usernameCanonical": "felix.weth@gmail.com",
        "vip": True,
    },
    "id": 22798,
    "li_city": "Berlin",
    "li_firstname": "Felix",
    "li_name": "Weth c/o Sailer",
    "li_plz": "10967",
    "li_street": "M\u00fcllenhoffstr.",
    "li_streetno": "16",
    "orderitem": [
        {
            "actual_price": 2.25,
            "amount": 1,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "articlenr": "11",
                "count_sold": 50,
                "count_view": 9,
                "descLong": "Herkunft: Deutschland\nKlasse: II\nVerband: Demeter\n",
                "gtin": "",
                "id": 2212890,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio Apfel Elstar vom Bio-Obsthof Augusting",
                "priceBrutto": 2.25,
                "priceNetto": 2.1,
                "sort": 0,
                "unity": "g",
                "unityAmount": 500,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225100,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 1.35,
            "amount": 1,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "angebot_kind": 1,
                "articlenr": "21",
                "count_sold": 50,
                "count_view": 15,
                "descLong": "Herkunft: Dominikanische Republik\nKlasse:\nVerband: EG-Bio\n",
                "gtin": "",
                "id": 2212900,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio Bananen",
                "priceBrutto": 1.35,
                "priceNetto": 1.26,
                "sort": 0,
                "unity": "g",
                "unityAmount": 500,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225101,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 1.5,
            "amount": 2,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "angebot_kind": 1,
                "articlenr": "30",
                "count_sold": 100,
                "count_view": 8,
                "descLong": "Herkunft: Deutschland\nKlasse:\nVerband: Bioland\n",
                "gtin": "",
                "id": 2212909,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio M\u00f6hren, violett Purple Sun",
                "priceBrutto": 1.5,
                "priceNetto": 1.4,
                "sort": 0,
                "unity": "g",
                "unityAmount": 500,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225102,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 2.25,
            "amount": 1,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "articlenr": "83",
                "count_sold": 50,
                "count_view": 9,
                "descLong": "Herkunft: Spanien\nKlasse: II\nVerband: EG-Bio \n",
                "gtin": "",
                "id": 2212962,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio Romatomaten",
                "priceBrutto": 2.25,
                "priceNetto": 2.1,
                "sort": 0,
                "unity": "g",
                "unityAmount": 500,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225103,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 3.5,
            "amount": 1,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "articlenr": "92",
                "count_sold": 50,
                "count_view": 8,
                "descLong": "Herkunft: Spanien\nKlasse: \nVerband: EG-Bio \n",
                "gtin": "",
                "id": 2212971,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio Zucchini, gr\u00fcn",
                "priceBrutto": 3.5,
                "priceNetto": 3.27,
                "sort": 0,
                "unity": "g",
                "unityAmount": 500,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225104,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 3.7,
            "amount": 1,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "articlenr": "65",
                "count_sold": 50,
                "count_view": 7,
                "descLong": "Herkunft: Deutschland\nKlasse:\nVerband: Naturland\n",
                "gtin": "",
                "id": 2212944,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio Rosenkohl",
                "priceBrutto": 3.7,
                "priceNetto": 3.45,
                "sort": 0,
                "unity": "g",
                "unityAmount": 500,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225105,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 2.5,
            "amount": 2,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "articlenr": "101",
                "count_sold": 100,
                "count_view": 6,
                "descLong": "Herkunft: Regional\nKlasse: \nVerband: Naturland\n",
                "gtin": "",
                "id": 2212980,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio ei care Eier 4 St Gr, M / L",
                "priceBrutto": 2.5,
                "priceNetto": 2.34,
                "sort": 0,
                "unity": "stk",
                "unityAmount": 1,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225106,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 1.5,
            "amount": 2,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "articlenr": "6",
                "count_sold": 100,
                "count_view": 8,
                "descLong": "Herkunft: Spanien\nKlasse: II \nVerband: EG-Bio\n",
                "gtin": "",
                "id": 2212885,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio Orangen Navelina Kal 2-3",
                "priceBrutto": 1.5,
                "priceNetto": 1.4,
                "sort": 0,
                "unity": "g",
                "unityAmount": 500,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225107,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 2.5,
            "amount": 1,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "angebot_kind": 1,
                "articlenr": "71",
                "count_sold": 50,
                "count_view": 4,
                "descLong": "Herkunft: Spanien\nKlasse: \nVerband: EG-Bio ",
                "gtin": "",
                "id": 2212950,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio Broccoli",
                "priceBrutto": 2.5,
                "priceNetto": 2.33,
                "sort": 0,
                "unity": "g",
                "unityAmount": 500,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225108,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 2.39,
            "amount": 1,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "articlenr": "39",
                "count_sold": 50,
                "count_view": 3,
                "descLong": "Herkunft: Frankreich\nKlasse: \nVerband:EG-Bio \n",
                "gtin": "",
                "id": 2212918,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio Gegarte Rote Bete, 500g, folienverpackt",
                "priceBrutto": 2.39,
                "priceNetto": 2.23,
                "sort": 0,
                "unity": "stk",
                "unityAmount": 1,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225109,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
        {
            "actual_price": 2.25,
            "amount": 1,
            "deliveryFee": False,
            "fkarticle": {
                "Amount": 1,
                "activated": True,
                "activatedByOperator": True,
                "angebot_kind": 1,
                "articlenr": "12",
                "count_sold": 50,
                "count_view": 8,
                "descLong": "Herkunft: Deutschland\nKlasse: II\nVerband: Demeter\n",
                "gtin": "",
                "id": 2212891,
                "last_modified": "2021-12-17T00:00:00+01:00",
                "name": "Bio Apfel Topaz vom Bio-Obsthof Augusting",
                "priceBrutto": 2.25,
                "priceNetto": 2.1,
                "sort": 0,
                "unity": "g",
                "unityAmount": 500,
                "useTraderDelivery": True,
                "ust": 7,
            },
            "id": 225110,
            "pickupStatus": {
                "color": "#508E9C",
                "id": 1,
                "name": "unpacked",
                "showInBulkEdit": True,
            },
            "variant": "0",
            "variants": [],
            "zustelltermin": 0,
            "zustelltermin_frei": "2021-12-18T17:00:00+01:00",
        },
    ],
    "re_city": "Berlin",
    "re_firstname": "Felix",
    "re_name": "Weth c/o Sailer",
    "re_plz": "10967",
    "re_street": "M\u00fcllenhoffstr.",
    "re_streetno": "16",
    "receipts": [],
    "zahlungsmethode": 1,
    "zustellart": 1,
}
