# This is a basic workflow to help you get started with Actions

name: CD

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false


jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Configure GPG Key
        env:
          GPG_KEY: ${{ secrets.GPG_KEY }}
        run: |
          echo -n "$GPG_KEY" | gpg --import

      - name: Reveal secrets
        run: |
          sudo apt install git-secret
          git-secret reveal

      - name: Add ssh key
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Setup tmate session
        env:
          HOSTNAME: ${{ secrets.PRODUCTION_HOSTNAME }}
        uses: mxschmitt/action-tmate@v3
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled }}

      - name: Login to target, build and setup
        env:
          TARGET: ${{ secrets.PRODUCTION_HOSTNAME }}
        run: |
          cat services/airflow/deploy.sh | ssh -A -o "StrictHostKeyChecking no" root@$TARGET